"""
Sentinel Drain - Multilingual Alert Hub API Routes
Provides endpoints for retrieving plain-language alerts in EN, HI, KN, TA
and dispatching emergency notifications to PHC Medical Officers.
"""

from fastapi import APIRouter
from typing import Dict, List, Any

from ..database import get_db_connection

router = APIRouter(prefix="/api/alerts", tags=["alerts"])

@router.get("/latest")
def get_latest_alerts(limit: int = 10):
    """Retrieves recent multilingual alerts generated by the multi-agent decision layer."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
    SELECT a.*, p.phc_name, p.district
    FROM alerts a
    LEFT JOIN phc_ops p ON a.phc_id = p.phc_id
    ORDER BY a.timestamp DESC
    LIMIT ?
    """, (limit,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(r) for r in rows]

@router.post("/dispatch/{alert_id}")
def dispatch_alert(alert_id: str, channel: str = "ALL"):
    """
    Simulates gateway dispatch of alert via SMS, WhatsApp, and Health Portal.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM alerts WHERE alert_id = ?", (alert_id,))
    alert = cursor.fetchone()
    if not alert:
        conn.close()
        return {"status": "ERROR", "message": "Alert not found."}

    cursor.execute("UPDATE alerts SET status = 'DISPATCHED_TO_FIELD' WHERE alert_id = ?", (alert_id,))
    conn.commit()
    conn.close()

    return {
        "status": "DISPATCH_CONFIRMED",
        "alert_id": alert_id,
        "channels": ["State Health Command Portal", "SMS (NHM Gateway)", "WhatsApp Health Officer Broadcast"],
        "recipients": [
            "PHC Medical Officer",
            "District Health Supply Coordinator",
            "Chief Medical Officer (CMO) Gorakhpur"
        ]
    }
